# Generated by Django 4.2 on 2024-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails', verbose_name='Миниатюра'),
        ),
    ]
