# Generated by Django 4.2 on 2024-06-11 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_customuser_avatar_customuser_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtoken',
            options={'verbose_name': 'Токен', 'verbose_name_plural': 'Токены'},
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterModelTable(
            name='customtoken',
            table='custom_token',
        ),
    ]
