# Generated by Django 4.2 on 2024-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0005_alter_customtoken_options_alter_customtoken_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpeg', upload_to='avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.jpeg', upload_to='thumbnails', verbose_name='Миниатюра'),
        ),
    ]
